name: Embed recipes in README

on:
  pull_request:
    branches:
      - main
jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: refs/heads/${{ github.head_ref }}

      - uses: technology-studio-forks/markdown-embed-code@v1.1.2
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          markdown: "README.md"
          token: ${{ secrets.GH_PA_TOKEN }}
          message: "docs(readme): updating recipes in readme"
          silent: true